# Generated by Django 2.1 on 2019-09-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre:')),
                ('apellido', models.CharField(max_length=45, verbose_name='apellido:')),
                ('dni', models.IntegerField(null=True)),
                ('domicilio', models.CharField(max_length=45, verbose_name='domicilio:')),
                ('telefono', models.CharField(max_length=45, verbose_name='telefono:')),
                ('mail', models.EmailField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=45, verbose_name='estado:')),
            ],
        ),
        migrations.CreateModel(
            name='forma_de_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.CharField(max_length=45, verbose_name='tipo_de_pago:')),
                ('precio', models.FloatField()),
                ('nombre_cliente', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=45)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=45, verbose_name='genero:')),
            ],
        ),
        migrations.CreateModel(
            name='habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_habitacion', models.CharField(max_length=40)),
                ('precio', models.IntegerField(null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.forma_de_pago')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='fecha_reserva')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha_ingreso')),
                ('fecha_salida', models.DateField(verbose_name='fecha_salida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('num_ambientes', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.reserva'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_de_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.tipo_de_habitacion'),
        ),
        migrations.AddField(
            model_name='detalle_reserva',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.habitacion'),
        ),
        migrations.AddField(
            model_name='detalle_reserva',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.pago'),
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.pago'),
        ),
        migrations.AddField(
            model_name='detalle_pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.reserva'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.genero'),
        ),
    ]
